### ISSUE TITLE
WunderBarMock can't deal with Getters in GraphQL-Returntypes that throw Exceptions

### ISSUE THREAD

**Issue by FChen12** [t1/wunderbar#256]
Consider a GraphQL-Query defined in a client-side API:
```
StuffApi {
   @Query
   Stuff getStuff();
}
```
where `Stuff` is:
```
class Stuff {
    ...
    int getXY() {
        if (someCondition) {
            return xy;
        }
        throw new SomeException();
    }
}
```
In a unit test where `@WunderBarApiConsumer(level = INTEGRATION)` and `StuffApi` is mocked via WunderBar,
`getStuff()` will wrongly return `RuntimeException: expected successful status code but got 500 Internal Server Error: null`.
Avoiding the prefix `get` will fix this.
Removing the exception will also fix this.

**Comment by t1** [comment]
I tried to reproduce this but couldn't. Could you provide a full reproducer?

**Comment by FChen12** [comment]
[issue256-reproducer.zip](https://github.com/t1/wunderbar/files/10529841/issue256-reproducer.zip)

During the creation of the reproducer, I noticed this log output:
```ERROR: UT005071: Undertow request failed HttpServerExchange{ POST /graphql}
javax.json.bind.JsonbException: Unable to serialize property 'data' from com.github.t1.wunderbar.junit.consumer.integration.GraphQlResponse
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:71)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:107)
	at org.eclipse.yasson.internal.Marshaller.serializeRoot(Marshaller.java:147)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:73)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:101)
	at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:126)
	at com.github.t1.wunderbar.junit.http.HttpResponse$HttpResponseBuilder.body(HttpResponse.java:177)
	at com.github.t1.wunderbar.junit.consumer.integration.GraphQlExpectation.handleRequest(GraphQlExpectation.java:54)
	at com.github.t1.wunderbar.junit.consumer.integration.IntegrationTestExpectations.handleRequest(IntegrationTestExpectations.java:65)
	at com.github.t1.wunderbar.junit.http.HttpServer.handle(HttpServer.java:55)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:59)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)
Caused by: javax.json.bind.JsonbException: Unable to serialize property 'something' from org.example.Stuff
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:71)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:107)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:125)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializeItem(AbstractContainerSerializer.java:194)
	at org.eclipse.yasson.internal.serializer.MapToObjectSerializer.serializeContainer(MapToObjectSerializer.java:100)
	at org.eclipse.yasson.internal.serializer.MapSerializer.serializeInternal(MapSerializer.java:167)
	at org.eclipse.yasson.internal.serializer.MapSerializer.serializeInternal(MapSerializer.java:32)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serialize(AbstractContainerSerializer.java:107)
	at org.eclipse.yasson.internal.serializer.AbstractContainerSerializer.serializerCaptor(AbstractContainerSerializer.java:125)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:121)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:69)
	... 17 more
Caused by: javax.json.bind.JsonbException: Error getting value on: Stuff(id=1)
	at org.eclipse.yasson.internal.model.ReflectionPropagation.getValue(ReflectionPropagation.java:112)
	at org.eclipse.yasson.internal.model.PropertyModel.getValue(PropertyModel.java:342)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.marshallProperty(ObjectSerializer.java:97)
	at org.eclipse.yasson.internal.serializer.ObjectSerializer.serializeInternal(ObjectSerializer.java:69)
	... 27 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.yasson.internal.model.ReflectionPropagation.lambda$acceptMethod$0(ReflectionPropagation.java:51)
	at org.eclipse.yasson.internal.model.ReflectionPropagation.getValue(ReflectionPropagation.java:110)
	... 30 more
Caused by: java.lang.RuntimeException
	at org.example.Stuff.getSomething(Stuff.java:20)
	... 36 more
```
	
Seems to be some Json serialization problem?

**Comment by t1** [comment]
Hmmm... you throw a `RuntimeException` (not a `SomeException`) when serialising data, so I would expect that. If you rename the getter to `xy`, it's not a getter anymore and jsonb only uses the getter for `id`. So this is not an issue.
